### ISSUE TITLE
Debug not working anymore?

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/ble-examples#75]
I cant seem to debug anymore.. for simplicity sake Ive come back to one of the ble examples (gapbutton) with the nrf51dk gcc target. Ive upgraded yotta and heres my yt ls, build logs, and debug session

```
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yt ls
ble-gapbutton 0.0.1
┣━ mbed-drivers 1.5.0
┃ ┣━ mbed-hal 1.3.0 yotta_modules/mbed-hal
┃ ┃ ┗━ mbed-hal-nordic 2.1.0 yotta_modules/mbed-hal-nordic
┃ ┃   ┗━ mbed-hal-nrf51822-mcu 2.2.0 yotta_modules/mbed-hal-nrf51822-mcu
┃ ┃     ┣━ nrf51-sdk 2.3.0 yotta_modules/nrf51-sdk
┃ ┃     ┗━ mbed-hal-nrf51dk 2.1.0 yotta_modules/mbed-hal-nrf51dk
┃ ┣━ cmsis-core 1.2.0 yotta_modules/cmsis-core
┃ ┃ ┗━ cmsis-core-nordic 1.1.0 yotta_modules/cmsis-core-nordic
┃ ┃   ┗━ cmsis-core-nrf51822 1.4.0 yotta_modules/cmsis-core-nrf51822
┃ ┣━ ualloc 1.3.0 yotta_modules/ualloc
┃ ┃ ┗━ dlmalloc 1.1.0 yotta_modules/dlmalloc
┃ ┣━ minar 1.3.0 yotta_modules/minar
┃ ┃ ┗━ minar-platform 1.1.0 yotta_modules/minar-platform
┃ ┃   ┗━ minar-platform-mbed 1.3.0 yotta_modules/minar-platform-mbed
┃ ┣━ core-util 1.8.0 yotta_modules/core-util
┃ ┣━ compiler-polyfill 1.3.0 yotta_modules/compiler-polyfill
┃ ┗━ greentea-client 1.1.0 yotta_modules/greentea-client
┗━ ble 2.6.0
  ┗━ ble-nrf51822 2.6.0 yotta_modules/ble-nrf51822

Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yotta --version
0.16.2
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ valinor --version
0.0.15
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ 

```

```
Last login: Wed Apr  6 13:03:58 on ttys001
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yt clean
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yt target nrf51dk-gcc
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yt build -d
info: generate for target: nrf51dk-gcc 1.0.0 at /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_targets/nrf51dk-gcc
GCC version is: 4.8.4
omit frame pointer for bootloader startup asm
suppressing warnings from nrf51-sdk
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/bin/arm-none-eabi-gcc
suppressing warnings from ble-nrf51822
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/build/nrf51dk-gcc
[16/147] Building C object ym/mbed-drivers/s.../yotta_modules/mbed-drivers/source/error.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/error.c: In function 'error':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/error.c:26:31: warning: unused parameter 'format' [-Wunused-parameter]
 __weak void error(const char* format, ...) {
                               ^
[19/147] Building C object ym/mbed-drivers/s...yotta_modules/mbed-drivers/source/assert.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/assert.c: In function 'mbed_assert_internal':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/assert.c:27:39: warning: unused parameter 'expr' [-Wunused-parameter]
 void mbed_assert_internal(const char *expr, const char *file, int line)
                                       ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/assert.c:27:57: warning: unused parameter 'file' [-Wunused-parameter]
 void mbed_assert_internal(const char *expr, const char *file, int line)
                                                         ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/assert.c:27:67: warning: unused parameter 'line' [-Wunused-parameter]
 void mbed_assert_internal(const char *expr, const char *file, int line)
                                                                   ^
[39/147] Building CXX object ym/mbed-drivers...a_modules/mbed-drivers/source/test_env.cpp.
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/test_env.cpp:17:0:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/mbed-drivers/test_env.h:20:2: warning: #warning mbed-drivers/test_env.h is deprecated. Please use greentea-client/test_env.h instead. [-Wcpp]
 #warning mbed-drivers/test_env.h is deprecated. Please use greentea-client/test_env.h instead.
  ^
[41/147] Building C object ym/mbed-drivers/s...tta_modules/mbed-drivers/source/rtc_time.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/rtc_time.c: In function 'set_time':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-drivers/source/rtc_time.c:49:22: warning: unused parameter 't' [-Wunused-parameter]
 void set_time(time_t t) {
                      ^
[54/147] Building C object ym/core-util/sour...tta_modules/core-util/source/assert_mbed.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c: In function 'core_util_runtime_error_internal':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:33:51: warning: unused parameter 'file' [-Wunused-parameter]
 void core_util_runtime_error_internal(const char *file, int line, const char* format, ...) {
                                                   ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:33:61: warning: unused parameter 'line' [-Wunused-parameter]
 void core_util_runtime_error_internal(const char *file, int line, const char* format, ...) {
                                                             ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:33:79: warning: unused parameter 'format' [-Wunused-parameter]
 void core_util_runtime_error_internal(const char *file, int line, const char* format, ...) {
                                                                               ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c: In function 'core_util_assert_internal':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:45:44: warning: unused parameter 'expr' [-Wunused-parameter]
 void core_util_assert_internal(const char *expr, const char *file, int line, const char* msg)
                                            ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:45:62: warning: unused parameter 'file' [-Wunused-parameter]
 void core_util_assert_internal(const char *expr, const char *file, int line, const char* msg)
                                                              ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:45:72: warning: unused parameter 'line' [-Wunused-parameter]
 void core_util_assert_internal(const char *expr, const char *file, int line, const char* msg)
                                                                        ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/assert_mbed.c:45:90: warning: unused parameter 'msg' [-Wunused-parameter]
 void core_util_assert_internal(const char *expr, const char *file, int line, const char* msg)
                                                                                          ^
[55/147] Building C object ym/core-util/sour...modules/core-util/source/critical_nordic.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/critical_nordic.c: In function 'core_util_critical_section_enter':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/critical_nordic.c:53:9: warning: passing argument 1 of 'sd_nvic_critical_region_enter' discards 'volatile' qualifier from pointer target type [enabled by default]
         sd_nvic_critical_region_enter(&_state._sd_state);
         ^
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/nrf_soc.h:45:0,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/core-util/source/critical_nordic.c:25:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/nrf_soc.h:495:49: note: expected 'uint8_t *' but argument is of type 'volatile uint8_t *'
 SVCALL(SD_NVIC_CRITICAL_REGION_ENTER, uint32_t, sd_nvic_critical_region_enter(uint8_t * p_is_nested_critical_region));
                                                 ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/nrf_svc.h:49:45: note: in definition of macro 'SVCALL'
   __attribute__((naked)) static return_type signature \
                                             ^
[84/147] Building C object ym/mbed-hal-nrf51...ed-hal-nrf51822-mcu.dir/source/us_ticker.c.
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-hal-nrf51822-mcu/source/us_ticker.c:21:0:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:194:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us) __attribute__((always_inline));
 ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:195:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us)
 ^
[85/147] Building C object ym/mbed-hal-nrf51...d-hal-nrf51822-mcu.dir/source/serial_api.c.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-hal-nrf51822-mcu/source/serial_api.c: In function 'serial_baud':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-hal-nrf51822-mcu/source/serial_api.c:107:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (baudrate<acceptedSpeeds[i][0]) {
                     ^
[118/147] Building C object ym/nrf51-sdk/sou...k/components/drivers_nrf/delay/nrf_delay.c.
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.c:36:0:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:194:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us) __attribute__((always_inline));
 ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:195:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us)
 ^
[123/147] Building C object ym/nrf51-sdk/sou...libraries/bootloader_dfu/dfu_app_handler.c.
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/libraries/bootloader_dfu/dfu_app_handler.c:43:0:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:194:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us) __attribute__((always_inline));
 ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h:195:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us)
 ^
[130/147] Building CXX object ym/ble/source/...modules/ble/source/services/DFUService.cpp.
In file included from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/ble_l2cap.h:45:0,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/ble_gatts.h:44,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/ble/ble_services/ble_dfu/ble_dfu.h:51,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/libraries/bootloader_dfu/dfu_app_handler.h:57,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/ble/ble/services/DFUService.h:26,
                 from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/ble/source/services/DFUService.cpp:19:
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/ble_l2cap.h:133:45: warning: unused parameter 'cid' [-Wunused-parameter]
 SVCALL(SD_BLE_L2CAP_CID_REGISTER, uint32_t, sd_ble_l2cap_cid_register(uint16_t cid));
                                             ^
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/nrf51-sdk/source/nordic_sdk/components/softdevice/s130/headers/nrf_svc.h:49:45: note: in definition of macro 'SVCALL'
   __attribute__((naked)) static return_type signature \
                                             ^
[146/147] Building CXX object source/CMakeFi...ble-examples/BLE_GAPButton/source/main.cpp.
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/source/main.cpp: In function 'void print_error(ble_error_t, const char*)':
/Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/source/main.cpp:36:11: warning: enumeration value 'BLE_ERROR_INTERNAL_STACK_FAILURE' not handled in switch [-Wswitch]
     switch(error) {
           ^
[147/147] Linking CXX executable source/ble-gapbutton
Memory usage for 'ble-gapbutton'
section              size
.data                 336
.bss                 1820
.heap               18324
.stack               2048
```

```
Jacobs-MacBook-Air:BLE_GAPButton jacobrosenthal$ yt debug
info: found ble-gapbutton at source/ble-gapbutton
info: preparing PyOCD gdbserver...
info: finding connected board...
info: DAP SWD MODE initialised
info: 4 hardware breakpoints, 0 literal comparators
info: CPU core is Cortex-M0
info: 2 hardware watchpoints
info: starting PyOCD gdbserver...
info: Telnet: server started on port 4444
info: GDB server started at port:3333
GNU gdb (GNU Tools for ARM Embedded Processors) 7.6.0.20140731-cvs
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-apple-darwin10 --target=arm-none-eabi".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/build/nrf51dk-gcc/source/ble-gapbutton...done.
info: One client connected!
0x0003dd16 in ?? ()
(gdb) where
#0  0x0003dd16 in ?? ()
#1  <signal handler called>
#2  0x0003c1b0 in ?? ()
#3  0x0003dda2 in ?? ()
#4  0x0003dda2 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) load
Loading section .text, size 0x1f9c4 lma 0x1c000
Loading section .ARM.exidx, size 0x8 lma 0x3b9c4
Loading section .data, size 0x150 lma 0x3b9cc
[====================] 100%
Start address 0x2eeac, load size 129820
Transfer rate: 2 KB/sec, 1909 bytes/write.
(gdb) where
#0  Reset_Handler ()
    at /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-hal-nrf51822-mcu/bootstrap_gcc/startup_nRF51822.S:112
(gdb) mon reset halt
(gdb) where
#0  Reset_Handler ()
    at /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/yotta_modules/mbed-hal-nrf51822-mcu/bootstrap_gcc/startup_nRF51822.S:112
(gdb) info b
No breakpoints or watchpoints.
(gdb) b app_start
Breakpoint 1 at 0x1e186: file /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/source/main.cpp, line 164.
(gdb) c
Continuing.
Note: automatically using hardware breakpoints for read-only addresses.

Program received signal SIGSEGV, Segmentation fault.
0x000006b0 in ?? ()
(gdb) where
#0  0x000006b0 in ?? ()
#1  <signal handler called>
Cannot access memory at address 0x20007ffc
Cannot access memory at address 0x20007ff8
(gdb) load
Loading section .text, size 0x1f9c4 lma 0x1c000
Loading section .ARM.exidx, size 0x8 lma 0x3b9c4
Loading section .data, size 0x150 lma 0x3b9cc
[====================] 100%
Start address 0x2eeac, load size 129820
Transfer rate: 11 KB/sec, 1909 bytes/write.
(gdb) info b
Num     Type           Disp Enb Address    What
1       breakpoint     keep y   0x0001e186 in app_start(int, char**) 
                                           at /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/source/main.cpp:164
(gdb) c
Continuing.
^C^CInterrupted while waiting for the program.
Give up (and stop debugging it)? (y or n) y
(gdb) quit
y
info: Telnet: server stopped
info: GDB server thread killed
project files have been generated in: /Users/jacobrosenthal/Downloads/ble-examples/BLE_GAPButton/build/nrf51dk-gcc/source
```

**Comment by jacobrosenthal** [comment]
So Ive fixed my issue on the nordic dev board. First I used the wrong target nrf51dk instead of mkit. Second ive found very similar errors if the softdevice isnt present. However Im still fighting this issue on my other target where it initially occured, but at least I have a known working now.
